"""Cargo.toml emitter for the C++ to Rust transpiler.

Generates workspace and per-crate Cargo.toml files from the IR, including
inter-crate dependencies (from the module dependency graph) and external
crate dependencies detected from usage patterns in the IR.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List, Optional, Set

from ir.nodes import (
    IRFile, IRItem, IRModule, IRStruct, IRTrait, IREnum, IRImplBlock,
    IRFunction, IRField, IRParam, IRType, IRConst, IRTypeAlias,
    IRMacro, IRUseDecl, IRBlock, IRVarDecl, IRExprStmt, IRCallExpr,
    IRNameRef, IRRawExpr, IRRawStmt,
)

if TYPE_CHECKING:
    from config import TranspilerConfig

logger = logging.getLogger(__name__)


# ── External dependency detection rules ──────────────────────────────────

# Each entry maps a pattern (found in type names, expressions, or use paths)
# to the external crate it implies.  The value is (crate_name, version_req).
_EXTERNAL_DEP_RULES: List[tuple] = [
    # bitflags crate
    ({"bitflags!", "bitflags::bitflags"}, ("bitflags", "2")),
    # parking_lot types
    ({"Mutex", "RwLock", "parking_lot::Mutex", "parking_lot::RwLock",
      "parking_lot::Condvar", "parking_lot::Once"}, ("parking_lot", "0.12")),
    # libc types
    ({"libc::", "c_void", "c_int", "c_uint", "c_char", "c_long", "c_ulong",
      "size_t", "ssize_t", "off_t", "pid_t"}, ("libc", "0.2")),
    # log crate
    ({"log::", "log::info", "log::warn", "log::error", "log::debug",
      "log::trace"}, ("log", "0.4")),
    # once_cell (still used by many crates even though std has LazyLock now)
    ({"once_cell::", "Lazy", "OnceCell"}, ("once_cell", "1")),
]

# Optional / feature-gated modules that need cfg features.
_FEATURE_GATED_MODULES: Dict[str, str] = {
    "wasm": "webassembly",
    "asmjs": "webassembly",
}


class CargoEmitter:
    """Generates Cargo.toml files for the transpiled workspace."""

    def __init__(self, config: TranspilerConfig) -> None:
        self._config = config

    # ── Public API ────────────────────────────────────────────────────────

    def emit_workspace(self, modules: List[str]) -> Path:
        """Write the top-level workspace ``Cargo.toml``.

        Args:
            modules: list of V8 module names (e.g. ``["base", "heap", ...]``).

        Returns:
            The path to the written workspace ``Cargo.toml``.
        """
        output_root = self._config.output_root
        output_root.mkdir(parents=True, exist_ok=True)

        lines: List[str] = []
        lines.append("# Auto-generated by the C++ to Rust transpiler.")
        lines.append("# Do not edit manually.")
        lines.append("")
        lines.append("[workspace]")
        lines.append('resolver = "2"')
        lines.append('members = ["crates/*"]')
        lines.append("")
        lines.append("[workspace.package]")
        lines.append('edition = "2021"')
        lines.append('version = "0.1.0"')
        lines.append("")

        # Optional: workspace-level dependency declarations so crates can
        # reference them with ``dep.workspace = true``.  We list the external
        # crates that any member might use.
        lines.append("[workspace.dependencies]")
        lines.append('bitflags = "2"')
        lines.append('libc = "0.2"')
        lines.append('log = "0.4"')
        lines.append('once_cell = "1"')
        lines.append('parking_lot = "0.12"')
        lines.append("")

        cargo_toml = output_root / "Cargo.toml"
        cargo_toml.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote workspace Cargo.toml (%d members)", len(modules))
        return cargo_toml

    def emit_crate(self, ir_module: IRModule) -> Path:
        """Write the ``Cargo.toml`` for a single crate.

        Returns:
            The path to the written crate ``Cargo.toml``.
        """
        crate_dir = self._config.output_root / "crates" / ir_module.crate_name
        crate_dir.mkdir(parents=True, exist_ok=True)

        lines: List[str] = []
        lines.append("# Auto-generated by the C++ to Rust transpiler.")
        lines.append("# Do not edit manually.")
        lines.append("")

        # [package]
        lines.append("[package]")
        lines.append(f'name = "{ir_module.crate_name}"')
        lines.append("version.workspace = true")
        lines.append("edition.workspace = true")
        lines.append("")

        # [features] (if any)
        features = self._collect_features(ir_module)
        if features:
            lines.append("[features]")
            for feat_name, feat_deps in sorted(features.items()):
                deps_str = ", ".join(f'"{d}"' for d in feat_deps)
                lines.append(f"{feat_name} = [{deps_str}]")
            lines.append("")

        # [dependencies]
        inter_crate_deps = self._collect_inter_crate_deps(ir_module)
        external_deps = self._detect_external_deps(ir_module)

        # Merge any explicitly declared external deps from the IRModule.
        for dep_name, dep_version in ir_module.external_deps.items():
            external_deps[dep_name] = dep_version

        if inter_crate_deps or external_deps:
            lines.append("[dependencies]")

            # Inter-crate (path) dependencies.
            for dep_crate in sorted(inter_crate_deps):
                # Determine optional / feature gate.
                dep_module = self._config.crate_to_module_name(dep_crate)
                feature_gate = _FEATURE_GATED_MODULES.get(dep_module)
                if feature_gate:
                    lines.append(
                        f'{dep_crate} = {{ path = "../{dep_crate}", optional = true }}'
                    )
                else:
                    lines.append(
                        f'{dep_crate} = {{ path = "../{dep_crate}" }}'
                    )

            # Blank separator between path deps and external deps.
            if inter_crate_deps and external_deps:
                lines.append("")

            # External crate dependencies.
            for dep_name in sorted(external_deps):
                dep_version = external_deps[dep_name]
                lines.append(f'{dep_name} = "{dep_version}"')

            lines.append("")

        cargo_toml = crate_dir / "Cargo.toml"
        cargo_toml.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote %s Cargo.toml", ir_module.crate_name)
        return cargo_toml

    # ── Inter-crate dependency collection ─────────────────────────────────

    def _collect_inter_crate_deps(self, ir_module: IRModule) -> List[str]:
        """Collect other v8 crates this module depends on.

        Uses the ``IRModule.dependencies`` list (populated by the mapper /
        dependency graph analysis) and also scans use-declarations for
        references to sibling crate names.
        """
        deps: Set[str] = set()

        # Explicit dependencies from the IR.
        for dep in ir_module.dependencies:
            # Normalise: accept either module names or crate names.
            if dep.startswith("v8-") or dep.startswith("v8_"):
                deps.add(dep.replace("_", "-"))
            else:
                crate = self._config.module_to_crate_name(dep)
                deps.add(crate)

        # Scan use declarations for crate references.
        for ir_file in ir_module.files:
            for use_decl in ir_file.uses:
                crate_ref = self._extract_crate_from_use(use_decl.path)
                if crate_ref and crate_ref != ir_module.crate_name:
                    deps.add(crate_ref)

        # Never depend on yourself.
        deps.discard(ir_module.crate_name)
        return sorted(deps)

    @staticmethod
    def _extract_crate_from_use(use_path: str) -> Optional[str]:
        """Extract a v8 crate name from a use path like ``v8_base::bits``.

        Returns the crate name (``v8-base``) or ``None`` if the path does
        not reference a v8 crate.
        """
        if not use_path:
            return None
        first_segment = use_path.split("::")[0]
        if first_segment.startswith("v8_"):
            # ``v8_base`` → ``v8-base``
            return first_segment.replace("_", "-")
        return None

    # ── External dependency detection ─────────────────────────────────────

    def _detect_external_deps(self, ir_module: IRModule) -> Dict[str, str]:
        """Scan the IR for usage patterns that imply external crate deps.

        Returns a dict of ``{crate_name: version_req}``.
        """
        # Collect all "interesting" strings from the IR: type names,
        # expression text, use paths, macro bodies, raw source fragments, etc.
        tokens = self._collect_tokens(ir_module)

        detected: Dict[str, str] = {}
        for patterns, (crate_name, version) in _EXTERNAL_DEP_RULES:
            for pattern in patterns:
                if pattern in tokens:
                    detected[crate_name] = version
                    break  # one match is enough for this crate

        return detected

    def _collect_tokens(self, ir_module: IRModule) -> str:
        """Build a single string of all identifiers / type names in the IR.

        This gives us a quick way to check for usage patterns without
        walking the full tree repeatedly for every rule.
        """
        parts: List[str] = []
        for ir_file in ir_module.files:
            self._collect_tokens_from_file(ir_file, parts)
        return " ".join(parts)

    def _collect_tokens_from_file(
        self, ir_file: IRFile, parts: List[str]
    ) -> None:
        """Append token strings from a single IRFile."""
        # Use declarations.
        for use_decl in ir_file.uses:
            parts.append(use_decl.path)

        # Items.
        for item in ir_file.items:
            self._collect_tokens_from_item(item, parts)

    def _collect_tokens_from_item(
        self, item: IRItem, parts: List[str]
    ) -> None:
        """Recursively collect identifier tokens from an IR item."""
        if isinstance(item, IRStruct):
            parts.append(item.name)
            for f in item.fields:
                self._collect_tokens_from_type(f.type, parts)
            for m in item.methods:
                self._collect_tokens_from_function(m, parts)
        elif isinstance(item, IRTrait):
            parts.append(item.name)
            for m in item.methods:
                self._collect_tokens_from_function(m, parts)
        elif isinstance(item, IREnum):
            parts.append(item.name)
            if item.underlying_type:
                self._collect_tokens_from_type(item.underlying_type, parts)
        elif isinstance(item, IRImplBlock):
            parts.append(item.struct_name)
            if item.trait_name:
                parts.append(item.trait_name)
            for m in item.methods:
                self._collect_tokens_from_function(m, parts)
        elif isinstance(item, IRFunction):
            self._collect_tokens_from_function(item, parts)
        elif isinstance(item, IRTypeAlias):
            parts.append(item.name)
            if item.target:
                self._collect_tokens_from_type(item.target, parts)
        elif isinstance(item, IRConst):
            parts.append(item.name)
            if item.type:
                self._collect_tokens_from_type(item.type, parts)
            if item.value:
                parts.append(item.value)
        elif isinstance(item, IRUseDecl):
            parts.append(item.path)
        elif isinstance(item, IRMacro):
            parts.append(item.name)
            if item.body:
                parts.append(item.body)

    def _collect_tokens_from_function(
        self, func: IRFunction, parts: List[str]
    ) -> None:
        """Collect tokens from a function's signature and body."""
        parts.append(func.name)
        for p in func.params:
            self._collect_tokens_from_type(p.type, parts)
        if func.return_type:
            self._collect_tokens_from_type(func.return_type, parts)
        if func.body:
            self._collect_tokens_from_block(func.body, parts)

    @staticmethod
    def _collect_tokens_from_type(ir_type: IRType, parts: List[str]) -> None:
        """Collect the type name and any generic arguments."""
        if ir_type is None:
            return
        parts.append(ir_type.name)
        if ir_type.cpp_name:
            parts.append(ir_type.cpp_name)
        for arg in ir_type.generic_args:
            CargoEmitter._collect_tokens_from_type(arg, parts)

    def _collect_tokens_from_block(
        self, block: IRBlock, parts: List[str]
    ) -> None:
        """Collect tokens from statements in a block (shallow scan)."""
        if block is None or block.statements is None:
            return
        for stmt in block.statements:
            if isinstance(stmt, IRVarDecl):
                if stmt.type:
                    self._collect_tokens_from_type(stmt.type, parts)
            elif isinstance(stmt, IRRawStmt):
                parts.append(stmt.cpp_source)
            elif isinstance(stmt, IRBlock):
                self._collect_tokens_from_block(stmt, parts)

    # ── Feature collection ────────────────────────────────────────────────

    @staticmethod
    def _collect_features(ir_module: IRModule) -> Dict[str, List[str]]:
        """Build the ``[features]`` table for this crate.

        Features come from:
        1. Explicit ``ir_module.features`` list.
        2. Feature-gated dependencies (e.g. wasm → webassembly).
        """
        features: Dict[str, List[str]] = {}

        # Explicit features.
        for feat in ir_module.features:
            if feat not in features:
                features[feat] = []

        # Feature gates implied by dependencies on gated modules.
        for dep in ir_module.dependencies:
            gate = _FEATURE_GATED_MODULES.get(dep)
            if gate:
                feature_deps = features.setdefault(gate, [])
                crate_name = f"v8-{dep.replace('_', '-')}"
                dep_feature = f"dep:{crate_name}"
                if dep_feature not in feature_deps:
                    feature_deps.append(dep_feature)

        # Ensure a "default" feature exists when there are other features.
        if features and "default" not in features:
            features["default"] = []

        return features
