"""Cargo.toml emitter for cpp2rust.

Generates workspace and per-crate Cargo.toml files from the dependency graph
built by DepWirer.  Crate membership is determined by the plugin's
crate_for_file() method.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional, Set

logger = logging.getLogger(__name__)


class CargoEmitter:
    """Generates Cargo.toml files for the transpiled workspace."""

    def __init__(self, plugin=None, dep_graph=None) -> None:
        self._plugin = plugin
        self._dep_graph = dep_graph  # DepWirer graph; may be None in early phases

    def emit_workspace(self, output_dir: Path) -> Path:
        """Write the top-level workspace Cargo.toml.

        Scans output_dir/crates/ for member crates and lists them.
        """
        output_dir.mkdir(parents=True, exist_ok=True)
        crates_dir = output_dir / "crates"

        # Discover existing crate directories
        members: List[str] = []
        if crates_dir.exists():
            members = sorted(
                d.name for d in crates_dir.iterdir() if d.is_dir()
            )

        lines: List[str] = [
            "# Auto-generated by cpp2rust — do not edit manually.",
            "",
            "[workspace]",
            'resolver = "2"',
            'members = ["crates/*"]',
            "",
            "[workspace.package]",
            'edition = "2021"',
            'version = "0.1.0"',
            "",
            "[workspace.dependencies]",
            'bitflags = "2"',
            'libc = "0.2"',
            'log = "0.4"',
            'once_cell = "1"',
            'parking_lot = "0.12"',
            "",
        ]

        cargo_toml = output_dir / "Cargo.toml"
        cargo_toml.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote workspace Cargo.toml (%d members)", len(members))

        # Write per-crate Cargo.toml for any discovered crates
        for crate_name in members:
            self._emit_crate(crates_dir / crate_name, crate_name)

        return cargo_toml

    def _emit_crate(self, crate_dir: Path, crate_name: str) -> Path:
        """Write Cargo.toml for a single crate."""
        crate_dir.mkdir(parents=True, exist_ok=True)
        src_dir = crate_dir / "src"
        src_dir.mkdir(parents=True, exist_ok=True)

        # Collect inter-crate deps from dep_graph
        inter_deps: List[str] = []
        if self._dep_graph is not None:
            inter_deps = sorted(
                self._dep_graph.get_deps(crate_name) or []
            )

        lines: List[str] = [
            "# Auto-generated by cpp2rust — do not edit manually.",
            "",
            "[package]",
            f'name = "{crate_name}"',
            "version.workspace = true",
            "edition.workspace = true",
            "",
        ]

        if inter_deps:
            lines.append("[dependencies]")
            for dep in inter_deps:
                lines.append(f'{dep} = {{ path = "../{dep}" }}')
            lines.append("")

        # Ensure a lib.rs exists so cargo check passes
        lib_rs = src_dir / "lib.rs"
        if not lib_rs.exists():
            lib_rs.write_text(
                "// Auto-generated placeholder — do not edit manually.\n",
                encoding="utf-8",
            )

        cargo_toml = crate_dir / "Cargo.toml"
        cargo_toml.write_text("\n".join(lines) + "\n", encoding="utf-8")
        logger.info("Wrote %s/Cargo.toml", crate_name)
        return cargo_toml
